---

- name: Install Apache2 and set timezone to Africa/Lagos
  hosts: all
  become: yes
  tasks:

  - name: update cache
    apt:
      update_cache: yes

  - name: Install Apache2    
    apt:
      name: apache2
      state: present

  - name: Set timezone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Display hostname and date
    shell: echo "<h1> hello world This is $(hostname -f) </h1>" > /var/www/html/index.html
    notify: restart_apache

  handlers:
  - name: restart_apache
    systemd:
      name: apache2
      state: restarted