name: terraform apply

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  provisioning:
    runs-on: ubuntu-latest
    steps:
    - uses: kciter/terraform-apply-for-aws-action@v3
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        variables: /project/variables.tf
        path: /project
